proxies:
  # Shadowsocks 节点 1
  - name: "美国-unknown 1"
    type: ss
    server: 23.154.136.100
    port: 8090
    cipher: aes-256-gcm
    password: PCn1k6SQnfO2X27

  # Shadowsocks 节点 2
  - name: "英国-unknown 2"
    type: ss
    server: 212.102.53.195
    port: 443
    cipher: aes-128-gcm
    password: shadowocks

  # VMess 节点
  - name: "中文-unknown"
    type: vmess
    server: 23.162.200.227
    port: 443
    uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
    alterId: 0
    cipher: auto
    network: ws
    ws-path: /linkvws
    tls: true

  # Shadowsocks 节点 3
  - name: "美国-unknown 3"
    type: ss
    server: 69.50.95.203
    port: 8882
    cipher: aes-256-cfb
    password: kDTwXYZ9toBckC4

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "美国-unknown 1"
      - "英国-unknown 2"
      - "中文-unknown"
      - "美国-unknown 3"
      - "DIRECT"

rules:
  - MATCH,Proxy
